// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4JX7zJjrIrz0mwaneMIEMdt-641IrXps',
    appId: '1:905397444760:web:845179197a3ac921a370ed',
    messagingSenderId: '905397444760',
    projectId: 'aars-2025',
    authDomain: 'aars-2025.firebaseapp.com',
    storageBucket: 'aars-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADQt0gkafebmNd130JGDXx4Ym0Fgzz22Q',
    appId: '1:905397444760:android:ae83110647c679eea370ed',
    messagingSenderId: '905397444760',
    projectId: 'aars-2025',
    storageBucket: 'aars-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vavrRbfl74QpNppb_9KoRJ73ugld-Jo',
    appId: '1:905397444760:ios:7e75c66b708c04aba370ed',
    messagingSenderId: '905397444760',
    projectId: 'aars-2025',
    storageBucket: 'aars-2025.firebasestorage.app',
    iosBundleId: 'com.example.aars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-vavrRbfl74QpNppb_9KoRJ73ugld-Jo',
    appId: '1:905397444760:ios:7e75c66b708c04aba370ed',
    messagingSenderId: '905397444760',
    projectId: 'aars-2025',
    storageBucket: 'aars-2025.firebasestorage.app',
    iosBundleId: 'com.example.aars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4JX7zJjrIrz0mwaneMIEMdt-641IrXps',
    appId: '1:905397444760:web:f2ef216702cfd14ea370ed',
    messagingSenderId: '905397444760',
    projectId: 'aars-2025',
    authDomain: 'aars-2025.firebaseapp.com',
    storageBucket: 'aars-2025.firebasestorage.app',
  );

}